version: '3.3'
services:
    elephant:
        container_name: elephant
        ports:
            - '4000:4000'
        volumes:
            - '${PWD}:/code'
        image: elephant
        stdin_open: true
        tty: true